name: CD Escriba Logger

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["CI Escriba Logger"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to PyPI

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    permissions:
      checks: write
      contents: read
      deployments: write
      id-token: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to PyPI
        run: pdm publish
