name: CI Escriba Logger

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: pdm-project/setup-pdm@v4

      - name: Install dependencies
        run: pdm install

      - name: Run tests
        run: |
          pdm run test:unit
          pdm run test:coverage_report_xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.18.0
        if: always()
        with:
          files: |
            tests/tmp/unit_result.xml

      - name: Upload test results to Codecov
        if: always()
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/tmp
          file: ./tests/tmp/unit_result.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        if: always()
        with:
          directory: ./tests/tmp/coverage
          slug: Strovsk/EscribaLogger
          env_vars: OS,PYTHON
          fail_ci_if_error: true
          files: ./coverage.unit.xml
          flags: unittests
          name: codecov-umbrella-escriba-logger
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
